export enum BookingTypes {
  CHECK_RECORD_REQUEST = "CHECK_RECORD_REQUEST",
  CHECK_RECORD_SUCCESS = "CHECK_RECORD_SUCCESS",
  CHECK_RECORD_FAILURE = "CHECK_RECORD_FAILURE",
  CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST",
  CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS",
  CREATE_BOOKING_FAILURE = "CREATE_BOOKING_FAILURE",
  CHECK_BOOKING_STATUS_REQUEST = "CHECK_BOOKING_STATUS_REQUEST",
  CHECK_BOOKING_STATUS_SUCCESS = "CHECK_BOOKING_STATUS_SUCCESS",
  CHECK_BOOKING_STATUS_FAILURE = "CHECK_BOOKING_STATUS_FAILURE",
  RESET_BOOKING_DATA = "RESET_BOOKING_DATA",
  RESET_BOOKING_STATUS_DATA = "RESET_BOOKING_STATUS_DATA",
}
