export enum OtpTypes {
  SEND_OTP_REQUEST = "SEND_OTP_REQUEST",
  SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS",
  SEND_OTP_FAILURE = "SEND_OTP_FAILURE",
  VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST",
  VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE",
  RESET_OTP_DATA = "RESET_OTP_DATA",
}
