export enum AppearanceTypes {
  LOAD_APPEARANCE_REQUEST = "LOAD_APPEARANCE_REQUEST",
  LOAD_APPEARANCE_SUCCESS = "LOAD_APPEARANCE_SUCCESS",
  LOAD_APPEARANCE_FAILURE = "LOAD_APPEARANCE_FAILURE",
  RESET_APPEARANCE_DATA = "RESET_APPEARANCE_DATA",
}
